export const newsItems = [
  {
    time: "12:44",
    league: "England",
    title: "ปืนเร่งคุยเอเยนต์กองกลางเป้าหมาย หลังคู่แข่งเริ่มขยับข้อเสนอ",
    summary: "รายงานระบุว่าทีมงานซื้อขายกำลังประเมินค่าตัวและค่าเหนื่อย ก่อนตัดสินใจยื่นข้อเสนออย่างเป็นทางการ",
    source: "เครดิต: สรุปจาก BeFootball Source Partner",
    sourceName: "BeFootball Source Partner",
    sourceType: "News API",
    originalUrl: "https://example.com/source/premier-league-transfer-rush",
    badge: "transfer",
    hot: true,
  },
  {
    time: "12:18",
    league: "Spain",
    title: "ราชันเตรียมพักตัวหลักเกมอุ่นเครื่อง เพื่อจัด load ก่อนทัวร์นาเมนต์ใหญ่",
    summary: "สตาฟฟ์โค้ชต้องการลดความเสี่ยงอาการล้าของผู้เล่นที่เพิ่งกลับมาซ้อมเต็มรูปแบบ",
    source: "เครดิต: SportsData Feed + Club Update",
    sourceName: "SportsData Feed",
    sourceType: "Sports Data API",
    originalUrl: "https://example.com/source/club-fitness-update",
    badge: "fitness",
  },
  {
    time: "11:52",
    league: "Italy",
    title: "งูใหญ่เปิดโต๊ะต่อสัญญาแนวรับตัวเก๋า พร้อมปรับบทบาทในซีซันใหม่",
    summary: "สโมสรยังมองว่าเจ้าตัวมีประโยชน์ทั้งในสนามและห้องแต่งตัว แต่ต้องตกลงรายละเอียดโบนัสเพิ่มเติม",
    source: "เครดิต: European News Wire",
    sourceName: "European News Wire",
    sourceType: "RSS/API",
    originalUrl: "https://example.com/source/inter-contract-update",
    badge: "official",
  },
  {
    time: "10:56",
    league: "Germany",
    title: "เสือใต้ยังไม่ปิดประตูดีลปีกดาวรุ่ง แม้ค่าตัวสูงกว่างบที่ตั้งไว้",
    summary: "ดีลยังอยู่ในขั้น monitoring โดยฝ่ายวิเคราะห์ต้องการดูข้อมูลความฟิตเพิ่มเติม",
    source: "เครดิต: Bundesliga RSS Monitor",
    sourceName: "Bundesliga RSS Monitor",
    sourceType: "RSS",
    originalUrl: "https://example.com/source/bayern-winger-monitoring",
    badge: "monitoring",
  },
];

export const rumors = [
  {
    status: "heating_up",
    title: "กองหน้าโปรตุเกสถูกเชื่อมโยงกับ 2 ทีมพรีเมียร์ลีก",
    summary: "ยังไม่มีการยืนยันจากสโมสร ต้นทางเป็นโพสต์จากนักข่าวตลาดซื้อขายและถูกพูดถึงต่อหลายแหล่ง",
    sourceName: "Transfer Desk X List",
    sourceType: "Official X embed",
    originalUrl: "https://example.com/source/transfer-desk-x-list",
    confidence: 48,
    heat: 82,
  },
  {
    status: "monitoring",
    title: "มิดฟิลด์ทีมชาติไทยมีรายงานว่าได้รับความสนใจจากเจลีก",
    summary: "ข้อมูลยังมาจากแหล่งเดียว ระบบตั้งสถานะ monitoring และต้องรอ human review ก่อนเผยแพร่จริง",
    sourceName: "Manual Admin Input",
    sourceType: "Manual",
    originalUrl: "https://example.com/source/manual-rumor-note",
    confidence: 35,
    heat: 51,
  },
  {
    status: "monitoring",
    title: "ทีมพรีเมียร์ลีกเริ่มเจรจาตัวแทนผู้รักษาประตูทีมชาติ",
    summary: "มีการสอบถามเงื่อนไขเบื้องต้น แต่สโมสรยังไม่ได้ยื่นข้อเสนออย่างเป็นทางการ",
    sourceName: "UK Football Desk",
    sourceType: "RSS",
    originalUrl: "https://example.com/source/goalkeeper-agent-talks",
    confidence: 55,
    heat: 64,
  },
  {
    status: "reliable",
    title: "แนวรับเซเรียอาใกล้บรรลุข้อตกลงสัญญาส่วนตัวกับทีมใหม่",
    summary: "หลายแหล่งรายงานตรงกันเรื่องเงื่อนไขส่วนตัว เหลือการเจรจาค่าตัวระหว่างสองสโมสร",
    sourceName: "Italian Transfer Wire",
    sourceType: "News API",
    originalUrl: "https://example.com/source/serie-a-defender-agreement",
    confidence: 76,
    heat: 79,
  },
  {
    status: "heating_up",
    title: "ปีกลาลีกาได้รับข้อเสนอยืมตัวพร้อมออปชันซื้อขาด",
    summary: "ต้นสังกัดพร้อมพิจารณาปล่อยยืมหากทีมปลายทางรับผิดชอบค่าเหนื่อยตามสัดส่วนที่กำหนด",
    sourceName: "LaLiga Market Monitor",
    sourceType: "RSS/API",
    originalUrl: "https://example.com/source/laliga-winger-loan",
    confidence: 63,
    heat: 85,
  },
  {
    status: "monitoring",
    title: "สโมสรลีกเอิงปฏิเสธข้อเสนอแรกสำหรับกองหน้าดาวรุ่ง",
    summary: "ข้อเสนอเปิดโต๊ะยังต่ำกว่ามูลค่าที่ต้นสังกัดตั้งไว้ และยังไม่มีข้อมูลเรื่องข้อเสนอรอบใหม่",
    sourceName: "French Football Report",
    sourceType: "News API",
    originalUrl: "https://example.com/source/ligue-one-striker-bid",
    confidence: 60,
    heat: 58,
  },
  {
    status: "heating_up",
    title: "สโมสรไทยลีกเร่งต่อสัญญากองกลางตัวหลักหลังมีทีมคู่แข่งสนใจ",
    summary: "ฝ่ายบริหารยื่นเงื่อนไขใหม่ให้นักเตะพิจารณา ขณะที่การพูดคุยกับทีมอื่นยังไม่มีเอกสารยืนยัน",
    sourceName: "Thai Football Update",
    sourceType: "Manual Review",
    originalUrl: "https://example.com/source/thai-league-contract-update",
    confidence: 58,
    heat: 73,
  },
  {
    status: "confirmed",
    title: "แบ็กบุนเดสลีกาผ่านขั้นตอนตรวจร่างกายก่อนเปิดตัว",
    summary: "สโมสรยืนยันกำหนดการตรวจร่างกายและอยู่ระหว่างจัดทำเอกสารขั้นสุดท้าย",
    sourceName: "Club Official Channel",
    sourceType: "Official",
    originalUrl: "https://example.com/source/bundesliga-fullback-medical",
    confidence: 92,
    heat: 88,
  },
  {
    status: "new",
    title: "สามสโมสรยุโรปส่งแมวมองดูฟอร์มดาวรุ่งเอเรดิวิซี",
    summary: "มีรายงานการเข้าชมเกมจริง แต่ยังไม่พบหลักฐานเรื่องการติดต่อหรือยื่นข้อเสนอ",
    sourceName: "European Scout Notes",
    sourceType: "Manual",
    originalUrl: "https://example.com/source/eredivisie-talent-scouted",
    confidence: 34,
    heat: 49,
  },
  {
    status: "reliable",
    title: "กองหน้าบราซิลได้รับข้อเสนอจากสองสโมสรในยุโรป",
    summary: "ตัวแทนนักเตะกำลังเปรียบเทียบแผนการใช้งานและเงื่อนไขโบนัส โดยยังไม่เลือกปลายทาง",
    sourceName: "South America Football Desk",
    sourceType: "RSS",
    originalUrl: "https://example.com/source/brazil-forward-europe-offers",
    confidence: 71,
    heat: 81,
  },
  {
    status: "denied",
    title: "ต้นสังกัดปฏิเสธข่าวผู้รักษาประตูจอมเก๋าเตรียมเลิกเล่น",
    summary: "สโมสรระบุว่านักเตะยังอยู่ในแผนฤดูกาลใหม่ และข่าวเดิมไม่มีข้อมูลสนับสนุนเพียงพอ",
    sourceName: "Club Official Statement",
    sourceType: "Official",
    originalUrl: "https://example.com/source/goalkeeper-retirement-denied",
    confidence: 95,
    heat: 42,
  },
  {
    status: "monitoring",
    title: "ดาวยิงแชมเปียนชิพถูกจับตาจากทีมน้องใหม่พรีเมียร์ลีก",
    summary: "ทีมงานวิเคราะห์ติดตามผลงานต่อเนื่อง แต่กระบวนการยังอยู่ในขั้นจัดทำรายชื่อเป้าหมาย",
    sourceName: "English Football Insider",
    sourceType: "RSS/API",
    originalUrl: "https://example.com/source/championship-striker-interest",
    confidence: 46,
    heat: 61,
  },
];

export const hotNews = [
  ["ตลาดอังกฤษเริ่มขยับหนัก หลายทีมเร่งปิดดีลก่อนทัวร์ปรีซีซัน", "England", "red"],
  ["วิเคราะห์ 5 ดาวรุ่งที่น่าจับตาในบอลยุโรปฤดูกาลนี้", "Europe", "green"],
  ["สรุปผลอุ่นเครื่องเมื่อคืน พร้อมประเด็นแท็กติกที่เห็นชัด", "All", ""],
];

export const fixtures = [
  ["บุรีรัมย์", "19:00", "บีจี ปทุม", "ไทยลีก"],
  ["แมนฯ ซิตี้", "21:30", "อาร์เซน่อล", "กระชับมิตร"],
  ["บาร์เซโลน่า", "02:00", "อินเตอร์", "Club friendly"],
];

export const standings = [
  ["Liverpool", 0, 0],
  ["Arsenal", 0, 0],
  ["Man City", 0, 0],
  ["Chelsea", 0, 0],
  ["Man United", 0, 0],
];

export const sourceRegistry = [
  {
    name: "BeFootball Source Partner",
    type: "News API",
    trustScore: 82,
    status: "active",
    lastFetched: "12:44",
  },
  {
    name: "SportsData Feed",
    type: "Sports Data API",
    trustScore: 90,
    status: "active",
    lastFetched: "12:18",
  },
  {
    name: "European News Wire",
    type: "RSS/API",
    trustScore: 76,
    status: "active",
    lastFetched: "11:52",
  },
  {
    name: "Bundesliga RSS Monitor",
    type: "RSS",
    trustScore: 68,
    status: "active",
    lastFetched: "10:56",
  },
  {
    name: "Transfer Desk X List",
    type: "Official X embed",
    trustScore: 61,
    status: "monitoring",
    lastFetched: "12:35",
  },
  {
    name: "Manual Admin Input",
    type: "Manual",
    trustScore: 50,
    status: "pending_review",
    lastFetched: "12:20",
  },
];
